export type TOfficeInfoData = {
  id: number;
  phone: string;
  supportEmail: string;
  officialEmail: string;
  supportPhone: string;
  ownerName: string;
  brandName: string;
  workingDayAndTime: string;
  closedDay: string;
  bin: string;
  hotline: string;
  officeAddress: string;
  secondaryOfficeAddress: string;
  latitude: string;
  longitude: string;
  linkedIn: string;
  instagram: string;
  facebook: string;
  twitter: string;
};
